### ISSUE TITLE
installation of mcl-22-282.tar.gz with fatal error: tingea/types.h: No such file or directory

### ISSUE THREAD

**Issue by azat-badretdin** [micans/mcl#13]
```
make[2]: Entering directory `/home/badrazat/mcl-22-282/src/clew'
gcc -DHAVE_CONFIG_H -I. -I../..  -I../../src -I../..   -g -O2 -pthread -MT scan.o -MD -MP -MF .deps/scan.Tpo -c -o scan.o scan.c
In file included from ../../src/impala/matrix.h:42:0,
                 from scan.h:61,
                 from scan.c:16:
../../src/impala/ivp.h:16:10: fatal error: tingea/types.h: No such file or directory
 #include "tingea/types.h"
          ^~~~~~~~~~~~~~~~

```
`make install` for the previous version mcl-14-137 is successful.

**Comment by micans** [comment]
Hi,
mcl requires installation of a C utility library called cimfomfa (it provides e.g. tingea/types.h). See https://github.com/micans/mcl#mcl for an installation recipe - it centers around the script `install-this-mcl.sh` that can be found at the top level in this respository.

**Comment by azat-badretdin** [comment]
Thanks. My trajectory was from `roary` installation page https://github.com/sanger-pathogens/Roary/blob/master/README.md#required-dependencies which goes to https://micans.org/mcl/ which goes to https://micans.org/mcl/src 

What is the best starting point for MCL? Maybe this info can be passed to `roary` folks.

**Comment by micans** [comment]
For Roary it may be best to go with mcl-14-137, as Roary depends on `mclblastline`. The latter is currently not shipped with `22-282`, I will probably rectify this in the future. If you installed mcl-14-137 then you may already have mclblastline. A further note is that there is no difference between the mcl clustering programs between those two versions; the changes are more to do with sibling programs (notes are in ChangeLog). The upshot is (1) there is very unlikely to be an issue if you mixed versions of programs between the two releases, and (2) if you use mcl-14-137 to get mclblastline + mcl then that's fine too as mcl has only had cosmetic changes.

I know that Debian may ship mcl-22-282 and back-port mclblastline for it, but the release is pending for other reasons.  The 22-282 version of mcl does bring some niggles such as  the new and changed installation procedure with added issue of missing mclblasline. I'll try to rectify/document issues as best as I can where appropriate.

**Comment by azat-badretdin** [comment]
Thanks! I guess the issue can be closed...
