### ISSUE TITLE
tag/release version 

### ISSUE THREAD

**Issue by pur80a** [micans/mcl#15]
Hi!
It would be great if you could tag and/or release the versions. Such that users know which version they are downloading. 
Thanks a lot

**Comment by micans** [comment]
Hello, fair point. I've retrospectively tagged commit acb812b5374c687d35486ef6ec393de79a3e5d82 with tag rel-22-282. In the future I'll aim to be a bit quicker.

General notice to anyone reading this, mcl software is installed from the releases on https://micans.org/mcl/ (and do read the installation instructions on the main GitHub mcl page https://github.com/micans/mcl), it is generally *not* advisable to attempt to install mcl by cloning the repository.

**Comment by pur80a** [comment]
Thanks a lot for the fast feedback!
