### ISSUE TITLE
make[3]: Nothing to be done for `install-data-am' error while executing "./install-this-mcl.sh "

### ISSUE THREAD

**Issue by Shanthosh29** [micans/mcl#18]

**Comment by joostvb-gh** [comment]
no problem there

it seems

 /usr/bin/install -c mcl '/Users/shanthosh_29/local/bin

has been executed, you should be able to run

/Users/shanthosh_29/local/bin/mcl --version

HTH, Bye,

Joost

**Comment by micans** [comment]
@joostvb-gh is entirely right; the installation was successful, it just had some output message that in some cases there was no need to do something (for example, no data needed copying). I will close this issue soon @Shanthosh29; you can always comment on it again if something is unclear or does not seem to be working.
