### ISSUE TITLE
Error: Multiple symbol definition error when including ... (mcl-21-257)

### ISSUE THREAD

**Issue by piosierra** [micans/mcl#3]
While trying to compile mcl I run into several of these errors, starting with `nu_meet_can' and generating a long string of them.
I am using gcc version 11.1.0.

**Comment by micans** [comment]
- What system are you compiling this on? Can you provide the output of `uname -a`, and if on Linux, the output of `cat /etc/os-release`.
- Are you using `build-mcl-21-257.sh` to build this?
- Can you copy the 20 lines of the terminal output before the first error appears, and the 40 lines after that.
- Alternatively, can you upload the file `mcl-21-257/config.log` (this is probably the best option).

**Comment by piosierra** [comment]
Hello, thanks for the fast answer.

- Linux thnkmnjr 5.14.18-1-MANJARO #1 SMP PREEMPT Fri Nov 12 20:24:59 UTC 2021 x86_64 GNU/Linux
- I tried with both scripts, an got the same result with both of them.

[config.log](https://github.com/micans/mcl/files/7660185/config.log)

**Comment by micans** [comment]
Ah, configure was fine of course. I will need more information about the `make` step. Can you
- use `build-mcl-21-257-b.sh` (http://micans.org/mcl/dev/build-mcl-21-257-b.sh) you will have to make it executable;
- run it and then upload the files
cimfomfa-21-257/cff.log
mcl-21-257/mcl.log

.. assuming both those files get made.

**Comment by piosierra** [comment]
Sure. Here you are.
[mcl.log](https://github.com/micans/mcl/files/7660851/mcl.log)
[cff.log](https://github.com/micans/mcl/files/7660852/cff.log)

**Comment by micans** [comment]
It looks as if things worked.
What does
`$HOME/local/bin/mcl --version`
produce?

**Comment by piosierra** [comment]
mcl has not been generated (nor even the local folder)
I receive the same errors as before, ending with: (sorry, spanish local)
...
/usr/bin/ld: ../impala/libimpala.a(stream.o):(.bss+0x20): definiciones múltiples de `nu_diff_sl'; clmformat.o:(.bss+0x20): primero se definió aquí
/usr/bin/ld: ../impala/libimpala.a(stream.o):(.bss+0x28): definiciones múltiples de `nu_diff_zip'; clmformat.o:(.bss+0x28): primero se definió aquí
/usr/bin/ld: ../impala/libimpala.a(stream.o):(.bss+0x30): definiciones múltiples de `nu_magic'; clmformat.o:(.bss+0x30): primero se definió aquí
/usr/bin/ld: ../impala/libimpala.a(stream.o):(.bss+0x38): definiciones múltiples de `mclx_n_thread_g'; clmformat.o:(.bss+0x38): primero se definió aquí
collect2: error: ld devolvió el estado de salida 1
make[3]: *** [Makefile:429: clmformat] Error 1
make[2]: *** [Makefile:327: all-recursive] Error 1
make[1]: *** [Makefile:383: all-recursive] Error 1
make: *** [Makefile:324: all] Error 2

**Comment by micans** [comment]
Ah yes, ahem the script had some issues. Can you remove the directories `mcl-21-257` and `cimfomfa-21-257`,  redownload the script and re-run (the change in the script is to also save STDERR to the log file), and then re-upload the log files.  I hope it is something simple, just can't see it yet.

**Comment by piosierra** [comment]
Thanks for your help.
I have run it without errors now. But I just see in $HOME/local/bin `cff_hashfile`  and `cff_let` Not sure if that is correct. I include the new log files.

[mcl.log](https://github.com/micans/mcl/files/7661077/mcl.log)

[cff.log](https://github.com/micans/mcl/files/7661080/cff.log)

**Comment by micans** [comment]
`cff_hashfile` and `cff_let` were installed by cimfomfa, I will disable that in future releases.
Can you do the procedure once more (with build-mcl-21-257-b.sh)? I have updated the build script by adding `-fcommon` to `CFLAGS`. If this solves it I'll need to clean up the code a bit, but it is nothing serious.

**Comment by piosierra** [comment]
Hello,
I got all these now. So it looks fine, I guess.

```
cff_hashfile  clmformat  mclcm        mcxarray     mcxi     mcxrand
cff_let       clxdo      mclpipeline  mcxassemble  mcxload  mcxsubs
clm           mcl        mcx          mcxdump      mcxmap
```
Nevertheless here you have the logs.

[mcl.log](https://github.com/micans/mcl/files/7661345/mcl.log)
[cff.log](https://github.com/micans/mcl/files/7661347/cff.log)

**Comment by micans** [comment]
Hello piosierra,
That fixed it and the log looks fine, so I'll close this issue. It's useful to me, I will compile the code with the option `-fno-common` and clean up the issues that you experienced.
Thanks,
Stijn

**Comment by micans** [comment]
The issue was that the variables in `src/impala/iface.h` needed an `extern` qualifier. A bit of a hindsigh ...

**Comment by piosierra** [comment]
Thanks a lot for the software and for your support!
