### ISSUE TITLE
compile on Apple M-series ARM64 processors

### ISSUE THREAD

**Issue by stephrom** [micans/mcl#30]
I would like to use MCL in combination with orthofinder on my MacBook Pro.
I tried to compile is but the configuration fails on a test of the gcc
At the configuration it doesn't seem to detect the actual architecture: arm64

~/Downloads/mcl % bash install-this-mcl.sh
--2024-06-04 21:48:39--  http://micans.org/mcl/src/mcl-22-282.tar.gz
Resolving micans.org (micans.org)... 2a00:1098:82::6:1, 46.235.227.111
Connecting to micans.org (micans.org)|2a00:1098:82::6:1|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2748263 (2,6M) [application/x-gzip]
Saving to: ‘mcl-22-282.tar.gz’

mcl-22-282.tar.gz                    100%[====================================================================>]   2,62M  6,79MB/s    in 0,4s

2024-06-04 21:48:39 (6,79 MB/s) - ‘mcl-22-282.tar.gz’ saved [2748263/2748263]

--2024-06-04 21:48:39--  http://micans.org/mcl/src/cimfomfa-22-273.tar.gz
Resolving micans.org (micans.org)... 2a00:1098:82::6:1, 46.235.227.111
Connecting to micans.org (micans.org)|2a00:1098:82::6:1|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 455547 (445K) [application/x-gzip]
Saving to: ‘cimfomfa-22-273.tar.gz’

cimfomfa-22-273.tar.gz               100%[====================================================================>] 444,87K  --.-KB/s    in 0,1s

2024-06-04 21:48:40 (3,60 MB/s) - ‘cimfomfa-22-273.tar.gz’ saved [455547/455547]

checking for a BSD-compatible install... /opt/local/bin/ginstall -c
checking whether build environment is sane... yes
/Users/strom/Downloads/mcl/cimfomfa-22-273/missing: Unknown `--is-lightweight' option
Try `/Users/strom/Downloads/mcl/cimfomfa-22-273/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
checking for a thread-safe mkdir -p... /opt/local/bin/gmkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking build system type... x86_64-apple-darwin23.5.0
checking host system type... x86_64-apple-darwin23.5.0
checking how to print strings... printf
checking whether make supports the include directive... yes (GNU style)
checking for gcc... /opt/homebrew/bin/gcc
checking whether the C compiler works... no
configure: error: in `/Users/strom/Downloads/mcl/cimfomfa-22-273':
configure: error: C compiler cannot create executables
See `config.log' for more details

**Comment by micans** [comment]
Hello, this issue might just be that you need to do one of the following

- sudo ./configure   # give permission to write somewhere below /usr
- ./configure --prefix=$HOME/local  # for example; a place where you write permisison.

The second is my prefered way of installing. Let me know if this works or not.

**Comment by micans** [comment]
I assume this solved the issue. Comment if this was not the case.
